(()=>{const qs=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const message=(t,type='success')=>{const e=qs('#reportMessage');e.textContent=t;e.dataset.type=type;e.hidden=!t};
(async()=>{const interviewId=new URLSearchParams(location.search).get('interview_id');if(!interviewId){message('Missing interview id.','error');qs('#reportLoading').hidden=true;return;}try{const session=await window.Auth.getSession();if(!session)return;const {data:interview,error:ie}=await window.supabaseApp.client.from('interviews').select('id,job_role,company,interview_type,difficulty,total_questions,status').eq('id',interviewId).eq('user_id',session.user.id).single();if(ie)throw ie;
 let {data:report,error:re}=await window.supabaseApp.client.from('performance_reports').select('*').eq('interview_id',interviewId).eq('user_id',session.user.id).maybeSingle();if(re)throw re;
 if(!report){message('Generating your report…');const {data,error}=await window.supabaseApp.client.functions.invoke('generate-report',{body:{interview_id:interviewId}});if(error)throw error;if(!data?.report)throw new Error('No performance report was returned.');report=data.report;}
 render(interview,report);qs('#reportLoading').hidden=true;qs('#reportContent').hidden=false;message('Performance report ready.');
 }catch(e){console.error(e);qs('#reportLoading').hidden=true;message(e.message||'Unable to generate the report.','error');}})();
function render(i,r){qs('[data-report-subtitle]').textContent=`${r.evaluated_questions} of ${i.total_questions} questions evaluated.`;qs('[data-role]').textContent=i.job_role;qs('[data-company]').textContent=`${i.company||'General'} · ${i.interview_type} · ${i.difficulty}`;qs('[data-overall]').textContent=`${Number(r.overall_score).toFixed(0)}/100`;
 const dims=[['Correctness',r.correctness],['Relevance',r.relevance],['Technical knowledge',r.technical_knowledge],['Completeness',r.completeness],['Clarity',r.clarity],['Communication',r.communication]];qs('[data-dimensions]').innerHTML=dims.map(([l,v])=>`<div class="dimension"><small>${esc(l)}</small><strong>${Number(v).toFixed(0)}/100</strong></div>`).join('');
 [['strengths',r.strengths],['weaknesses',r.weaknesses],['recommendations',r.recommendations]].forEach(([name,items])=>{qs(`[data-${name}]`).innerHTML=(Array.isArray(items)?items:[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>No items recorded.</li>';});
 const p=r.proctoring_summary||{};qs('[data-answered]').textContent=r.answered_questions;qs('[data-evaluated]').textContent=r.evaluated_questions;qs('[data-face]').textContent=`${p.face_presence_seconds||0}s`;qs('[data-multiple]').textContent=p.multiple_faces_events||0;qs('[data-out]').textContent=`${p.out_of_frame_events||0} (${p.out_of_frame_seconds||0}s)`;qs('[data-away]').textContent=p.head_away_events||0;qs('[data-posture]').textContent=p.posture_deviation_events||0;qs('[data-camera]').textContent=p.camera_permission||'unknown';}
})();