import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
function extractJson(text:string){const c=text.trim().replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/```$/i,"").trim();try{return JSON.parse(c)}catch{const s=c.indexOf("{");const e=c.lastIndexOf("}");if(s>=0&&e>s)return JSON.parse(c.slice(s,e+1));throw new Error("Invalid JSON returned by AI provider.")}}
function normalize(raw:any){const list=(v:any)=>Array.isArray(v)?v.map(x=>String(x).trim()).filter(Boolean).slice(0,5):[]; const out={strengths:list(raw?.strengths),weaknesses:list(raw?.weaknesses),recommendations:list(raw?.recommendations)}; if(!out.strengths.length||!out.weaknesses.length||!out.recommendations.length) throw new Error("AI returned an incomplete report."); return out;}
async function callProvider(provider:string,prompt:string){
 const model=provider==='groq'?(Deno.env.get('GROQ_MODEL')||'openai/gpt-oss-20b'):provider==='openrouter'?(Deno.env.get('OPENROUTER_MODEL')||'openrouter/free'):(Deno.env.get('GEMINI_MODEL')||'gemini-3.8-flash');
 if(provider==='groq'){const key=Deno.env.get('GROQ_API_KEY');if(!key)throw new Error('GROQ_API_KEY is not configured.');const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,temperature:.2,messages:[{role:'system',content:'You create concise interview performance reports and return valid JSON only.'},{role:'user',content:prompt}],response_format:{type:'json_object'}})});const raw=await r.text();if(!r.ok)throw Object.assign(new Error('Groq request failed'),{status:r.status});const d=JSON.parse(raw);return {data:extractJson(d?.choices?.[0]?.message?.content||''),model};}
 if(provider==='openrouter'){const key=Deno.env.get('OPENROUTER_API_KEY');if(!key)throw new Error('OPENROUTER_API_KEY is not configured.');const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json","HTTP-Referer":"https://supabase.com/","X-Title":"AI Interview Preparation System"},body:JSON.stringify({model,temperature:.2,messages:[{role:'system',content:'You create concise interview performance reports and return valid JSON only.'},{role:'user',content:prompt}],response_format:{type:'json_object'}})});const raw=await r.text();if(!r.ok)throw Object.assign(new Error('OpenRouter request failed'),{status:r.status});const d=JSON.parse(raw);return {data:extractJson(d?.choices?.[0]?.message?.content||''),model};}
 const key=Deno.env.get('GEMINI_API_KEY');if(!key)throw new Error('GEMINI_API_KEY is not configured.');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});const raw=await r.text();if(!r.ok)throw Object.assign(new Error('Gemini request failed'),{status:r.status});const d=JSON.parse(raw);return {data:extractJson(d?.candidates?.[0]?.content?.parts?.[0]?.text||''),model};
}
function avg(rows:any[],key:string){if(!rows.length)return 0;return Math.round((rows.reduce((s,r)=>s+Number(r[key]||0),0)/rows.length)*100)/100;}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Method not allowed'},405);
 const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anon||!service)return json({error:'Server Supabase configuration is incomplete.'},500);
 const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({error:'Authentication required.'},401);
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error:ue}=await userClient.auth.getUser();if(ue||!user)return json({error:'Invalid authentication token.'},401);
 let body:any={};try{body=await req.json()}catch{return json({error:'Invalid JSON body.'},400)};const interviewId=String(body.interview_id||'');if(!interviewId)return json({error:'interview_id is required.'},400);
 const admin=createClient(url,service);
 const {data:interview, error:ie}=await admin.from('interviews').select('id,user_id,job_role,company,interview_type,difficulty,total_questions,status').eq('id',interviewId).eq('user_id',user.id).single();if(ie||!interview)return json({error:'Interview not found.'},404);
 const {data:questions,error:qe}=await admin.from('questions').select('id,question_text,category,question_order').eq('interview_id',interviewId).order('question_order',{ascending:true});if(qe)return json({error:'Unable to load interview questions.'},500);
 const qids=(questions||[]).map(q=>q.id);
 const {data:answers,error:ae}=await admin.from('answers').select('id,question_id,answer_text,answer_method').eq('user_id',user.id).in('question_id',qids);if(ae)return json({error:'Unable to load interview answers.'},500);
 const aids=(answers||[]).map(a=>a.id);let evals:any[]=[];if(aids.length){const {data:ev,error:ee}=await admin.from('evaluations').select('id,answer_id,question_id,score,correctness,relevance,technical_knowledge,completeness,clarity,communication,feedback,suggested_answer,provider,model').eq('user_id',user.id).in('answer_id',aids);if(ee)return json({error:'Unable to load answer evaluations.'},500);evals=ev||[];}
 if(!evals.length)return json({error:'No evaluated answers found. Evaluate at least one answer first.'},400);
 const metrics={score:avg(evals,'score'),correctness:avg(evals,'correctness'),relevance:avg(evals,'relevance'),technical_knowledge:avg(evals,'technical_knowledge'),completeness:avg(evals,'completeness'),clarity:avg(evals,'clarity'),communication:avg(evals,'communication')};
 const {data:behavior}=await admin.from('behavior_metrics').select('camera_permission,face_presence_seconds,multiple_faces_events,out_of_frame_events,out_of_frame_seconds,head_away_events,posture_deviation_events,monitoring_started_at,monitoring_ended_at').eq('interview_id',interviewId).eq('user_id',user.id).maybeSingle();
 const digest=evals.map((e,i)=>{const q=(questions||[]).find(x=>x.id===e.question_id);const a=(answers||[]).find(x=>x.id===e.answer_id);return `Question ${q?.question_order||i+1}: ${q?.question_text||''}\nScore: ${e.score}/100\nCorrectness: ${e.correctness}, Relevance: ${e.relevance}, Technical: ${e.technical_knowledge}, Completeness: ${e.completeness}, Clarity: ${e.clarity}, Communication: ${e.communication}\nFeedback: ${e.feedback}\nAnswer: ${(a?.answer_text||'').slice(0,1200)}`}).join('\n\n');
 const prompt=`Create a concise overall interview performance report. Do not invent candidate facts. Base every point only on the provided evaluation data. Return exactly JSON: {"strengths":[""],"weaknesses":[""],"recommendations":[""]}. Each array should contain 2-5 short actionable items.\nRole: ${interview.job_role}\nCompany: ${interview.company||'General'}\nInterview type: ${interview.interview_type}\nDifficulty: ${interview.difficulty}\nAggregated scores: ${JSON.stringify(metrics)}\nEvaluated answers: ${evals.length}/${questions?.length||0}\n\nEvaluation evidence:\n${digest}`;
 const provider=(Deno.env.get('AI_PROVIDER')||'groq').toLowerCase();let result:any;try{result=await callProvider(provider,prompt)}catch(e){return json({error:e instanceof Error?e.message:'Report generation failed.'},502)}
 let narrative;try{narrative=normalize(result.data)}catch(e){return json({error:e instanceof Error?e.message:'Invalid report generated.'},502)}
 const row={interview_id:interviewId,user_id:user.id,answered_questions:(answers||[]).length,evaluated_questions:evals.length,overall_score:metrics.score,correctness:metrics.correctness,relevance:metrics.relevance,technical_knowledge:metrics.technical_knowledge,completeness:metrics.completeness,clarity:metrics.clarity,communication:metrics.communication,strengths:narrative.strengths,weaknesses:narrative.weaknesses,recommendations:narrative.recommendations,proctoring_summary:behavior||{},provider,model:result.model};
 const {data:saved,error:se}=await admin.from('performance_reports').upsert(row,{onConflict:'interview_id'}).select('*').single();if(se)return json({error:'Report was generated but could not be saved.'},500);
 return json({report:saved});
});
